{
 "title": "Finnhub RealTime Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1000ms",
 "templating": {
  "list": [
   {
    "name": "ticker",
    "label": "Company Ticker",
    "query": {
     "query": "SELECT DISTINCT symbol FROM market. Trades;"
    }
   }
  ]
 },
 "panels": [
  { "title": "Stock Price", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ticker" },
  {
   "title": "Price BTC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "select symbol, price, trade_timestamp from trades where symbol = '$ticker' and trade_timestamp>$__timeFrom and trade_timestamp<$__timeTo;\n\n"
    }
   ]
  },
  {
   "title": "Average price*volume from last 15 seconds",
   "type": "table",
   "gridPos": { "h": 20, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "target": "select symbol, price_volume_multiply, ingest_timestamp from running_averages_15_sec where symbol='$ticker';"
    }
   ]
  },
  {
   "title": "Volume BTC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 11 },
   "targets": [
    {
     "target": "select symbol, volume, trade_timestamp from trades where symbol = '$ticker' and trade_timestamp>$__timeFrom and trade_timestamp<$__timeTo;"
    }
   ]
  }
 ]
}